import Swagger from '../../docs/snippets/swagger.mdx'

export function Documentation() {
  return (
    <article>
      <header className="fern-gap flex w-full flex-col justify-between md:flex-row md:items-end">
        <h2 className="mb-2 flex flex-col gap-2 text-2xl font-medium text-gray-500 dark:text-gray-400">
          <span>Your own documentation</span>

          <span className="text-gradient z-10 from-violet-400 to-blue-500 text-7xl font-semibold">
            in 1 line
          </span>
        </h2>

        <div className="flex max-w-md flex-col gap-2 md:pr-4 md:text-base dark:font-medium">
          <p>It's not magic</p>

          <p>
            <span>With deep integration with OpenAPI schema</span>
            <br />
            <span>Elysia can generate Swagger documentation for your API out of the box</span>
          </p>
        </div>
      </header>

      <div className="preview">
        <img
          src="/assets/scalar-preview-dark.webp"
          alt="Scalar documentation generated by Elysia using Elysia Swagger plugin"
        />

        <div className="showcase">
          <Swagger />
        </div>
      </div>
    </article>
  )
}
