# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Synchronize GitHub repository labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml

jobs:
  synchronize:
    name: Synchronize GitHub repository labels

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Synchronize GitHub repository labels with '.github/labels.yml' manifest
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
